# Generated by Django 3.1 on 2020-08-10 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CryptocurrencyInfo',
            fields=[
                ('symbol', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('fcas_rating', models.CharField(max_length=64)),
                ('fcas_score', models.FloatField()),
                ('source_datetime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='StockInfo',
            fields=[
                ('symbol', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('gross_profit', models.FloatField()),
                ('quartely_revenue_growth', models.FloatField()),
                ('source_datetime', models.DateTimeField()),
            ],
        ),
    ]
