# Generated by Django 3.1 on 2020-08-10 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader_simulator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128)),
                ('investment_symbol', models.CharField(max_length=32)),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
